### ISSUE TITLE
Glue with the backend

### ISSUE THREAD

**Issue by luisivan** [helpdao/donation-portal#2]
[First implementation of the backend is ready](https://github.com/helpdao/donation-backend/) (except for the description field of the help squads). It'd be nice to plug both together!

**Comment by manolingam** [comment]
Need a deployed instance of the backend API to do the fetch.

**Comment by luisivan** [comment]
@manolingam can you run it locally for the moment?

**Comment by manolingam** [comment]
@luisivan It's possible to run it locally. But one needs to have both the front-end and back-end repositories cloned in their system to simultaneously start both the servers.

**Comment by luisivan** [comment]
yeah, that's fine @manolingam

**Comment by manolingam** [comment]
Alright, will work on it.

**Comment by manolingam** [comment]
Backend is now connected to the frontend. Great Job! @cbrzn
