### ISSUE TITLE
Host frontend on GitHub pages

### ISSUE THREAD

**Issue by luisivan** [helpdao/donation-portal#20]
Should be trivial https://create-react-app.dev/docs/deployment/#github-pages

**Comment by w0xter** [comment]
I deployed the Page in this [branch](https://github.com/helpdao/donation-portal/tree/gh-pages) to test if we can run the test mode without the TLS/SSL certificate, but I don't have access to the repo configuration so I can't set up the github page

**Comment by luisivan** [comment]
No prob, just gave you permissions!
