### ISSUE TITLE
Help squad creation

### ISSUE THREAD

**Issue by luisivan** [helpdao/donation-portal#3]
We should allow users to create new help squads with:
- Name
- Description
- DAO address
- Chat invite link

To stop spam, we could also add either [a captcha](https://www.google.com/recaptcha/intro/v3.html) or social login (login with Facebook/Twitter/VK, etc.).

Social login would actually be cool so that donors can see who created the squad and a link to their socials.

**Comment by manolingam** [comment]
Working on.

**Comment by manolingam** [comment]
Created a [pull request](https://github.com/helpdao/donation-portal/pull/4) with the template for new squad creation
